language: python

python:
     - "3.6.3"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install overalls

services:
  - postgresql

script:
  - coverage run -m pytest
  - coverage xml
  - coverage report
  - nosetests --with-coverage --cover-tests

after_success:
  - coveralls