language: python

python:
     - "3.6.3"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install overalls

script:
  - coverage run -m pytest
  - coverage xml
  - coverage report

after_success:
  - coveralls